import {
	type ZodType,
	type ZodAny,
	type ZodArray,
	type ZodBigInt,
	type ZodBoolean,
	type ZodCatch,
	type ZodCustom,
	type ZodDate,
	type ZodDefault,
	type ZodEnum,
	type ZodBase64,
	type ZodBase64URL,
	type ZodFile,
	type ZodFunction,
	type ZodGUID,
	type ZodIntersection,
	type ZodLazy,
	type ZodLiteral,
	type ZodMap,
	type ZodNaN,
	type ZodNever,
	type ZodNonOptional,
	type ZodNull,
	type ZodNullable,
	type ZodNumber,
	type ZodObject,
	type ZodOptional,
	type ZodPipe,
	type ZodPrefault,
	type ZodPromise,
	type ZodReadonly,
	type ZodRecord,
	type ZodSet,
	type ZodString,
	type ZodStringFormat,
	type ZodSuccess,
	type ZodSymbol,
	type ZodTemplateLiteral,
	type ZodTransform,
	type ZodTuple,
	type ZodUndefined,
	type ZodUnion,
	type ZodUnknown,
	type ZodVoid,
	type ZodCIDRv4,
	type ZodCIDRv6,
	type ZodCUID,
	type ZodCUID2,
	type ZodCustomStringFormat,
	type ZodEmoji,
	type ZodE164,
	type ZodEmail,
	type ZodIPv4,
	type ZodIPv6,
	type ZodJWT,
	type ZodKSUID,
	type ZodNanoID,
	type ZodULID,
	type ZodURL,
	type ZodUUID,
	type ZodXID,
} from "zod";

export type ZodTypeUnion =
	| ZodAny
	| ZodArray
	| ZodBigInt
	| ZodBoolean
	| ZodCatch
	| ZodCustom
	| ZodDate
	| ZodDefault
	| ZodEnum
	| ZodFile
	| ZodFunction
	| ZodIntersection
	| ZodLazy
	| ZodLiteral
	| ZodMap
	| ZodNaN
	| ZodNever
	| ZodNonOptional
	| ZodNull
	| ZodNullable
	| ZodNumber
	| ZodObject
	| ZodOptional
	| ZodPipe
	| ZodPrefault
	| ZodPromise
	| ZodReadonly
	| ZodRecord
	| ZodSet
	| ZodString
	| ZodStringFormat
	| ZodSuccess
	| ZodSymbol
	| ZodTemplateLiteral
	| ZodTransform
	| ZodTuple
	| ZodUndefined
	| ZodUnion
	| ZodUnknown
	| ZodVoid
	| ZodType
	| ZodCustomStringFormat
	| ZodBase64
	| ZodBase64URL
	| ZodCIDRv4
	| ZodCIDRv6
	| ZodCUID
	| ZodCUID2
	| ZodEmoji
	| ZodE164
	| ZodEmail
	| ZodGUID
	| ZodIPv4
	| ZodIPv6
	| ZodJWT
	| ZodKSUID
	| ZodNanoID
	| ZodULID
	| ZodURL
	| ZodUUID
	| ZodXID;
