import {
	type ZodType,
	type ZodAny,
	type ZodArray,
	type ZodBigInt,
	type ZodBoolean,
	type ZodCatch,
	type ZodCustom,
	type ZodDate,
	type ZodDefault,
	type ZodEnum,
	type ZodFile,
	type ZodFunction,
	type ZodIntersection,
	type ZodLazy,
	type ZodLiteral,
	type ZodMap,
	type ZodNaN,
	type ZodNever,
	type ZodNonOptional,
	type ZodNull,
	type ZodNullable,
	type ZodNumber,
	type ZodObject,
	type ZodOptional,
	type ZodPipe,
	type ZodPrefault,
	type ZodPromise,
	type ZodReadonly,
	type ZodRecord,
	type ZodSet,
	type ZodString,
	type ZodSuccess,
	type ZodSymbol,
	type ZodTemplateLiteral,
	type ZodTransform,
	type ZodTuple,
	type ZodUndefined,
	type ZodUnion,
	type ZodUnknown,
	type ZodVoid,
} from "zod";

export type ZodTypeUnion =
	| ZodAny
	| ZodArray
	| ZodBigInt
	| ZodBoolean
	| ZodCatch
	| ZodCustom
	| ZodDate
	| ZodDefault
	| ZodEnum
	| ZodFile
	| ZodFunction
	| ZodIntersection
	| ZodLazy
	| ZodLiteral
	| ZodMap
	| ZodNaN
	| ZodNever
	| ZodNonOptional
	| ZodNull
	| ZodNullable
	| ZodNumber
	| ZodObject
	| ZodOptional
	| ZodPipe
	| ZodPrefault
	| ZodPromise
	| ZodReadonly
	| ZodRecord
	| ZodSet
	| ZodString
	| ZodSuccess
	| ZodSymbol
	| ZodTemplateLiteral
	| ZodTransform
	| ZodTuple
	| ZodUndefined
	| ZodUnion
	| ZodUnknown
	| ZodVoid
	| ZodType;
