name: computed-version

on: 
  pull_request:
    branches:
      - develop
    types:
      - opened
      - edited
      - synchronize

jobs:
  computed-version:
    runs-on: ubuntu-latest
    steps:
      - name: title checker
        uses: thehanimo/pr-title-checker@v1.4.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          configuration_path: ".github/workflows/develop@check-title.json"

      - name: get current version
        uses: duplojs/action-semver@v0.3.0
        id: semver
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_OWNER: ${{ github.repository_owner }}
          GITHUB_REPO: zod-accelerator
          GITHUB_BRANCHE: develop
          REGEXP_PATCH: '^fix'
          REGEXP_MINOR: '^feat'
          REGEXP_MAJOR: '^break'
          MAJOR_START_AT: 1
          OUTPUT_FORMAT: '{MAJOR}.{MINOR}.{PATCH}-beta'
          CURRENT_PULL_REQUEST_TITLE: ${{ github.event.pull_request.title }}

      - name: see version
        run: echo "${{ steps.semver.outputs.COMPUTED_VERSION }}"

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Target version : `${{ steps.semver.outputs.COMPUTED_VERSION }}`.
          mode: upsert
          comment_tag: version