name: check-title

on: 
  pull_request:
    branches:
      - develop
    types:
      - opened
      - edited
      - synchronize

jobs:
  check-title:
    runs-on: ubuntu-latest
    steps:
      - uses: thehanimo/pr-title-checker@v1.4.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pass_on_octokit_error: false
          configuration_path: ".github/workflows/develop@check-title.json"